version: '3'

output: prefixed

includes:
  release: Taskfile.release.yml

tasks:
  run:
    cmds:
      - go run ./cmd/kz

  build:
    cmds:
      - mkdir -p ./bin
      - go build --ldflags "-extldflags -static -X 'main.Version=${VERSION}'" -o ./bin/kz ./cmd/kz
    env:
      CGO_ENABLED: '0'
      VERSION: ${VERSION:-main}

  test:
    cmds:
      - go test -v ./...
