version: '3'

output: prefixed

includes:
  release: Taskfile.release.yml
  test: Taskfile.test.yml

tasks:
  run:
    cmds:
      - go run ./cmd/kz

  build:
    cmds:
      - mkdir -p ./bin
      - go build --ldflags "-extldflags -static -X 'github.com/hpcsc/kz/internal/cmd.Version=${VERSION}'" -o ./bin/kz ./cmd/kz
    env:
      CGO_ENABLED: '0'
      VERSION: ${VERSION:-main}

  setup-git-hooks:
    cmds:
      - git config core.hooksPath ./hooks
