name: CI

on:
  push: {}

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - name: Run shellcheck
      run: task test:shellcheck

    - name: Build
      run: task build

    - name: Run unit test
      run: task test:unit

    - name: Run e2e test
      run: task test:e2e

    - name: Run vulnerabilities check
      run: task test:vulnerabilities
